
\" ----------------------------- nflood man page -------------------------------
.TH nflood 6 "DATE" vVERSION "nflood vVERSION"

\"---------------------------------- NAME --------------------------------------
.SH NAME
nflood \- Flood-It puzzle game on the terminal.

\"-------------------------------- SYNOPSIS ------------------------------------
.SH SYNOPSIS
nflood
.RB [ -h ]
.RB [ -v ]

\"------------------------------- DESCRIPTION ----------------------------------
.SH DESCRIPTION
.PP
nFlood is a simple clone of the Flood-It puzzle game.

.PP
You need to fill the whole board with a single color.
To do that, alternate between them, flooding with the
minimum number of moves possible.

.B Controls:
.RS
.BR "Mouse Click         " "Changes flood color"

.BR "1-6                 " "Changes flood color"

.BR "q                   " "Quits the game at any time"

.BR "r                   " "Restart game"
.RE

\"--------------------------------- OPTIONS ------------------------------------
.SH OPTIONS

.TP
.B "-h, --help"
Display the help text.

.TP
.B "-v, --version"
Display game version and build date.


\"----------------------------------- FILES -------------------------------------
.SH FILES
.BR "$(HOME)/.local/share/nflood/nflood.scores" "     User high scores"


\"---------------------------------- AUTHORS -----------------------------------
.SH AUTHORS
Alexandre Dantas <eu@alexdantas.net>.
Yu-Jie Lin <livibetter@gmail.com>

\"---------------------------------- WEBSITE -----------------------------------
.SH WWW
http://nflood.alexdantas.net/

